### ISSUE TITLE
Enforce tool version

### ISSUE THREAD

**Issue by novadev94** [MELD-labs/github-artifacts#4]
Currently the script `run.sh` checks if there's a local executable available before downloading the **latest** pre-built binaries. However, it doesn't enforce the version in both cases, which can cause some inconsistencies. For example, the `import-export-comma-style` option is only available in `fourmolu 0.6.0.0`.

**Comment by kk-hainq** [comment]
Yeah, the current setup makes very little sense:
- Changing the version in the pre-commit doesn't affect the tools' version to be used.
- Even worse, each run is non-deterministic as the same version here could fetch, say, a new breaking version of `fourmolu` to destroy the pre-commit setup of downstream users. A project with no changes could still get slapped in the face each time `fourmolu-binaries` bumps.
- We have 64 repositories and counting, why should we spend non-trivial resources maintaining such a poor setup...
